"""SD-Turbo fallback engine: 4-step masked img2img continuation.

Uses the sd-turbo snapshot already in the HF cache (fp32 weights, loaded
fp16). Different architecture from BrushNet - not affected by the Turing
fp16 corruption seen with PowerPaint on torch cu128. Bands are generated by
img2img over the whole composite; the orchestrator re-pastes the original
afterwards, so the byte guarantee is unaffected.
"""
import logging
import time

import numpy as np

from config import config

log = logging.getLogger("h2v.sdturbo")
ENGINE = "sd-turbo"

_STRENGTH = 0.85
_STEPS = 4


def available() -> bool:
    try:
        from huggingface_hub import snapshot_download
        return bool(snapshot_download("stabilityai/sd-turbo",
                                      local_files_only=True))
    except Exception:
        return False


def _turbo_snapshot():
    from huggingface_hub import snapshot_download
    return snapshot_download("stabilityai/sd-turbo", local_files_only=True)


def fill(canvas_rgb: np.ndarray, mask_u8: np.ndarray) -> np.ndarray:
    import cv2
    import torch
    from PIL import Image
    from pipeline.vrac import model_slot

    gen_long = min(768, max(canvas_rgb.shape[:2]))
    scale = gen_long / max(canvas_rgb.shape[:2])
    gw = max(320, 8 * round(canvas_rgb.shape[1] * scale / 8))
    gh = max(320, 8 * round(canvas_rgb.shape[0] * scale / 8))
    small = cv2.resize(canvas_rgb, (gw, gh), interpolation=cv2.INTER_AREA)

    def _load():
        from diffusers import AutoPipelineForImage2Image
        # This GPU's fp16 compute path is faulty (NaN corruption + inverted
        # throughput), so default to fp32 on CUDA. FORCE_FP16=true overrides
        # on healthy hardware.
        dtype = torch.float16 if (config.device() == "cuda"
                                  and config.FORCE_FP16) else torch.float32
        pipe = AutoPipelineForImage2Image.from_pretrained(
            _turbo_snapshot(), torch_dtype=dtype,
            safety_checker=None, requires_safety_checker=False)
        if config.device() == "cuda":
            pipe.enable_attention_slicing()
            try:
                pipe.to("cuda")
            except torch.cuda.OutOfMemoryError:
                log.warning("sd-turbo fp32 OOM -> sequential CPU offload")
                pipe.enable_sequential_cpu_offload()
        else:
            pipe.enable_attention_slicing()
        pipe.set_progress_bar_config(disable=True)
        return pipe

    def _run(pipe):
        g = torch.Generator("cpu").manual_seed(int(time.time()) & 0xFFFF)
        with torch.inference_mode():
            out = pipe(prompt="high quality photo, sharp, detailed scene",
                       image=Image.fromarray(small),
                       strength=_STRENGTH, num_inference_steps=_STEPS,
                       guidance_scale=0.0, generator=g).images[0]
        return np.array(out.convert("RGB"))

    with model_slot(ENGINE, _load) as pipe:
        filled_small = _run(pipe)

    return cv2.resize(filled_small,
                      (canvas_rgb.shape[1], canvas_rgb.shape[0]),
                      interpolation=cv2.INTER_CUBIC)
